# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Toutes les classes de src/ deviennent automatiquement des services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # 🔐 Processor pour hasher le password automatiquement
    App\State\UserPasswordHasherProcessor:
        arguments:
            $processor: '@api_platform.doctrine.orm.state.persist_processor'
